# fly.toml app configuration file generated for gpstrakergt02a on 2024-11-09T22:22:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpstrakergt02a'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 6666
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
